<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Buku;
use App\Models\Kategori;

class BukuSeeder extends Seeder
{
    public function run(): void
    {
        // Ambil ID kategori berdasarkan nama agar tidak hardcode ID
        $kat = Kategori::pluck('id', 'nama');

        $bukus = [
            [
                'judul'          => 'Laskar Pelangi',
                'penulis'        => 'Andrea Hirata',
                'penerbit'       => 'Bentang Pustaka',
                'tahun_terbit'   => 2005,
                'edisi'          => 'Revisi',
                'jumlah_halaman' => 534,
                'bahasa'         => 'Indonesia',
                'kategori_id'    => $kat['Fiksi'] ?? 1,
                'deskripsi'      => 'Sebuah novel semi-autobiografi yang mengisahkan perjuangan anak-anak miskin di Belitung yang berjuang untuk mendapatkan pendidikan layak dengan penuh semangat dan impian yang tak pernah padam.',
                'stok'           => 5,
                'isbn'           => '9789793062792',
                'visibility'     => Buku::VIS_DATA_SYNOPSIS,
            ],
            [
                'judul'          => 'Atomic Habits',
                'penulis'        => 'James Clear',
                'penerbit'       => 'Penguin Random House',
                'tahun_terbit'   => 2018,
                'edisi'          => '1',
                'jumlah_halaman' => 320,
                'bahasa'         => 'Indonesia',
                'kategori_id'    => $kat['Non-Fiksi'] ?? 2,
                'deskripsi'      => 'Panduan praktis membangun kebiasaan baik dan menghilangkan kebiasaan buruk. James Clear menawarkan sistem perubahan perilaku berbasis sains yang terbukti efektif melalui perubahan 1% setiap harinya.',
                'stok'           => 8,
                'isbn'           => '9780735211292',
                'visibility'     => Buku::VIS_FULL,
            ],
            [
                'judul'          => 'Sapiens: Sejarah Ringkas Umat Manusia',
                'penulis'        => 'Yuval Noah Harari',
                'penerbit'       => 'KPG (Kepustakaan Populer Gramedia)',
                'tahun_terbit'   => 2015,
                'edisi'          => 'Terjemahan',
                'jumlah_halaman' => 512,
                'bahasa'         => 'Indonesia',
                'kategori_id'    => $kat['Sejarah'] ?? 4,
                'deskripsi'      => 'Yuval Noah Harari menulusuri perjalanan Homo Sapiens dari peradaban purba hingga era modern, mengungkap bagaimana kognisi, pertanian, dan kapitalisme membentuk dunia yang kita tinggali hari ini.',
                'stok'           => 3,
                'isbn'           => '9786024240387',
                'visibility'     => Buku::VIS_DATA_SYNOPSIS,
            ],
            [
                'judul'          => 'Clean Code: A Handbook of Agile Software Craftsmanship',
                'penulis'        => 'Robert C. Martin',
                'penerbit'       => 'Prentice Hall',
                'tahun_terbit'   => 2008,
                'edisi'          => '1',
                'jumlah_halaman' => 464,
                'bahasa'         => 'Inggris',
                'kategori_id'    => $kat['Sains & Teknologi'] ?? 3,
                'deskripsi'      => 'Uncle Bob Martin mengajarkan prinsip-prinsip menulis kode bersih yang mudah dipahami, dirawat, dan dikembangkan. Wajib dibaca oleh setiap software engineer yang ingin kode berkualitas tinggi.',
                'stok'           => 4,
                'isbn'           => '9780132350884',
                'visibility'     => Buku::VIS_FULL,
            ],
            [
                'judul'          => 'Rich Dad Poor Dad',
                'penulis'        => 'Robert T. Kiyosaki',
                'penerbit'       => 'Gramedia Pustaka Utama',
                'tahun_terbit'   => 2000,
                'edisi'          => 'Edisi Terbaru',
                'jumlah_halaman' => 244,
                'bahasa'         => 'Indonesia',
                'kategori_id'    => $kat['Ekonomi & Bisnis'] ?? 5,
                'deskripsi'      => 'Perbandingan pola pikir tentang uang antara ayah miskin dan ayah kaya. Buku ini mengubah cara jutaan orang memandang kekayaan, investasi, dan kebebasan finansial.',
                'stok'           => 10,
                'isbn'           => '9786020342122',
                'visibility'     => Buku::VIS_DATA_SYNOPSIS,
            ],
            [
                'judul'          => 'Filosofi Teras',
                'penulis'        => 'Henry Manampiring',
                'penerbit'       => 'Kompas',
                'tahun_terbit'   => 2018,
                'edisi'          => '1',
                'jumlah_halaman' => 320,
                'bahasa'         => 'Indonesia',
                'kategori_id'    => $kat['Filsafat'] ?? 8,
                'deskripsi'      => 'Panduan filsafat Stoisisme yang relevan dengan kehidupan modern Indonesia. Henry Manampiring menjelaskan bagaimana Stoikisme membantu menghadapi kekhawatiran, kemarahan, dan tekanan sehari-hari.',
                'stok'           => 6,
                'isbn'           => '9786024123208',
                'visibility'     => Buku::VIS_DATA_SYNOPSIS,
            ],
            [
                'judul'          => 'Al-Quran dan Terjemahannya',
                'penulis'        => 'Departemen Agama RI',
                'penerbit'       => 'Lembaga Percetakan Al-Quran',
                'tahun_terbit'   => 2022,
                'edisi'          => 'Terbaru',
                'jumlah_halaman' => 604,
                'bahasa'         => 'Arab-Indonesia',
                'kategori_id'    => $kat['Agama & Spiritualitas'] ?? 9,
                'deskripsi'      => 'Al-Quran lengkap 30 juz dilengkapi terjemahan bahasa Indonesia yang disahkan oleh Kementerian Agama Republik Indonesia, edisi revisi terbaru dengan tata letak yang mudah dibaca.',
                'stok'           => 15,
                'isbn'           => '9786021543207',
                'visibility'     => Buku::VIS_DATA_ONLY,
            ],
            [
                'judul'          => 'Sehat Tanpa Obat',
                'penulis'        => 'dr. Tan Shot Yen',
                'penerbit'       => 'Qanita',
                'tahun_terbit'   => 2016,
                'edisi'          => '2',
                'jumlah_halaman' => 286,
                'bahasa'         => 'Indonesia',
                'kategori_id'    => $kat['Kesehatan'] ?? 7,
                'deskripsi'      => 'dr. Tan Shot Yen membahas pendekatan holistik terhadap kesehatan melalui pola makan alami, gaya hidup aktif, dan manajemen stres. Panduan hidup sehat yang berbasis riset dan pengalaman klinis.',
                'stok'           => 4,
                'isbn'           => '9786021580622',
                'visibility'     => Buku::VIS_DATA_SYNOPSIS,
            ],
            [
                'judul'          => 'Bumi Manusia',
                'penulis'        => 'Pramoedya Ananta Toer',
                'penerbit'       => 'Lentera Dipantara',
                'tahun_terbit'   => 1980,
                'edisi'          => 'Cetak Ulang 2023',
                'jumlah_halaman' => 535,
                'bahasa'         => 'Indonesia',
                'kategori_id'    => $kat['Fiksi'] ?? 1,
                'deskripsi'      => 'Novel epik pertama dari Tetralogi Buru karya Pramoedya Ananta Toer. Mengisahkan Minke, pemuda Jawa terdidik di zaman kolonial Belanda yang jatuh cinta dan melawan ketidakadilan.',
                'stok'           => 7,
                'isbn'           => '9789799731234',
                'visibility'     => Buku::VIS_FULL,
            ],
            [
                'judul'          => 'Introduction to Algorithms',
                'penulis'        => 'Cormen, Leiserson, Rivest, Stein',
                'penerbit'       => 'MIT Press',
                'tahun_terbit'   => 2022,
                'edisi'          => '4',
                'jumlah_halaman' => 1312,
                'bahasa'         => 'Inggris',
                'kategori_id'    => $kat['Sains & Teknologi'] ?? 3,
                'deskripsi'      => 'Buku teks algoritma paling komprehensif di dunia. Mencakup analisis kompleksitas, struktur data, teknik desain algoritma, dan topik lanjutan seperti pemrograman paralel dan teori bilangan.',
                'stok'           => 2,
                'isbn'           => '9780262046305',
                'visibility'     => Buku::VIS_DATA_ONLY,
            ],
            [
                'judul'          => 'Pendidikan Karakter: Membangun Generasi Emas',
                'penulis'        => 'Prof. Dr. Zubaedi, M.Ag.',
                'penerbit'       => 'Kencana Prenada Media',
                'tahun_terbit'   => 2011,
                'edisi'          => '2',
                'jumlah_halaman' => 296,
                'bahasa'         => 'Indonesia',
                'kategori_id'    => $kat['Pendidikan'] ?? 6,
                'deskripsi'      => 'Kajian mendalam tentang urgensi pendidikan karakter dalam sistem pendidikan nasional Indonesia. Membahas strategi implementasi nilai-nilai moral dan budi pekerti di lingkungan sekolah dan keluarga.',
                'stok'           => 9,
                'isbn'           => '9786021734605',
                'visibility'     => Buku::VIS_DATA_ONLY,
            ],
            [
                'judul'          => 'Batik: Seni dan Tradisi Indonesia',
                'penulis'        => 'Harini Muntasib & Lili Sugiarti',
                'penerbit'       => 'Balai Pustaka',
                'tahun_terbit'   => 2013,
                'edisi'          => '1',
                'jumlah_halaman' => 188,
                'bahasa'         => 'Indonesia',
                'kategori_id'    => $kat['Seni & Budaya'] ?? 10,
                'deskripsi'      => 'Eksplorasi lengkap tentang seni batik Nusantara, mulai dari sejarah, teknik pembuatan, motif-motif khas dari berbagai daerah, hingga perkembangan batik modern yang diakui UNESCO sebagai warisan dunia.',
                'stok'           => 6,
                'isbn'           => '9789794073125',
                'visibility'     => Buku::VIS_DATA_SYNOPSIS,
            ],
        ];

        foreach ($bukus as $data) {
            Buku::firstOrCreate(
                ['isbn' => $data['isbn']],
                $data
            );
        }
    }
}
